# .github/workflows/add-repository-label.yml

name: Add repository label

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label:
    uses: craftcms/.github/.github/workflows/add-repository-label.yml@v3